### ISSUE TITLE
Extract "Contributing" text at the bottom of resource pages into a separate reusable component

### ISSUE THREAD

**Issue by theackstack** [mssablog/mssablog.github.io#20]
Currently, most of the resource pages on the open-source site contain a "Contributing" section at the bottom of the page, with a link to the contributing guide for more information.

The text for this section is the same across all pages.  The problem is if this text gets changed, it needs to be updated independently on every page it's on.

Separate out this "Contributing" section into some kind of reusable component that can be inserted at the bottom of each page, so that the text only needs to be stored in one place and can be more easily updated across all pages.

**Comment by jedington** [comment]
![ScreenShot_20210221022842](https://user-images.githubusercontent.com/25874804/108619794-c59fea80-73ec-11eb-8e67-ea227ae5fad7.png)
Done--MSSA student input
