### ISSUE TITLE
Make resource tiles same height

### ISSUE THREAD

**Issue by theackstack** [mssablog/mssablog.github.io#37]
On several pages, the height of tiles currently varies based on the amount of text in each one.  Find a way to make the tiles equal height.

**Comment by jedington** [comment]
![ScreenShot_20210221014017](https://user-images.githubusercontent.com/25874804/108618741-24159a80-73e6-11eb-8d4d-145de642b7c6.png)

Depends on how you want this done tbh. Also added a small hover animation for fun.
edit: ` height:calc(40vh - 60px);`
Done--MSSA student input
